spring:
  application:
    name: CMSC4375 - Restaurant COVID Tracker
  datasource:
    initialization-mode: NEVER
    url: jdbc:mysql://localhost:3306/cmsc4375_lab3
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

